[package]
name = "lyrs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
genius-rs = "0.2.1"
ansi_term = "0.12.1"
pager = "0.16.0"
tokio = {version = "1.5.0", features = ["full"]}